-- Generated by ChatGPT, 14 April 2023
-- Modified by Capt Brian Yarbrough

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ALU_tb is
end ALU_tb;

architecture Behavioral of ALU_tb is

    component ALU is
        Port ( i_op : in  std_logic_vector (2 downto 0);
               i_A : in  signed(7 downto 0);
               i_B : in  signed(7 downto 0);
               o_num : out  signed(7 downto 0);
               o_flag : out  std_logic_vector (2 downto 0)
        );
    end component ALU;
    
    signal w_op : std_logic_vector(2 downto 0);
    signal w_A : signed(7 downto 0);
    signal w_B : signed(7 downto 0);
    signal w_num : signed(7 downto 0);
    signal w_flag : std_logic_vector(2 downto 0);
    
begin

    uut: ALU
        port map (
            i_op => w_op,
            i_A => w_A,
            i_B => w_B,
            o_num => w_num,
            o_flag => w_flag
        );
        
    process
    begin
        w_op <= "000";
        w_A <= to_signed(1, 8);
        w_B <= to_signed(1, 8);
        wait for 10 ns;
        assert (w_num = to_signed(1 + 1, 8)) and (w_flag = "100") report "bad op" severity error;
        wait for 10 ns;
        
        w_op <= "001";
        w_A <= to_signed(3, 8);
        w_B <= to_signed(7, 8);
        wait for 10 ns;
        assert (w_num = to_signed(3 - 7, 8)) and (w_flag = "000") report "bad op" severity error;
        wait for 10 ns;
        
        w_op <= "000";
        w_A <= to_signed(120, 8);
        w_B <= to_signed(10, 8);
        wait for 10 ns;
        assert (w_num = to_signed(120 + 10, 8)) and (w_flag = "010") report "bad op" severity error;
        wait for 10 ns;
        
        w_op <= "001";
        w_A <= to_signed(0, 8);
        w_B <= to_signed(-127, 8);
        wait for 10 ns;
        assert (w_num = to_signed(-127, 8)) and (w_flag = "010") report "bad op" severity error;
        wait for 10 ns;


        w_op <= "010";  -- OR
        w_A <= "01010001";
        w_B <= "00110100";
        wait for 10 ns;
        assert (w_num = "01100101") and (w_flag = "100") report "bad op" severity error;
        wait for 10 ns;
        
        w_op <= "011";  -- AND
        w_A <= "01010001";
        w_B <= "00110100";
        wait for 10 ns;
        assert (w_num = "00010000") and (w_flag = "100") report "bad op" severity error;
        wait for 10 ns;
                
        w_op <= "100";  -- LLS
        w_A <= "00001000";
        w_B <= "00000010";
        wait for 10 ns;
        assert (w_num = "00100000") and (w_flag = "100") report "bad op" severity error;
        wait for 10 ns;
                        
        w_op <= "101";  -- RLS
        w_A <= "00001000";
        w_B <= "00000010";
        wait for 10 ns;
        assert (w_num = "00000010") and (w_flag = "100") report "bad op" severity error;
        wait for 10 ns;
        
        wait;
    end process;
    
end Behavioral;
